### ISSUE TITLE
goimports doesn't run automatically on save

### ISSUE THREAD

**Issue by fabdarice** [DisposaBoy/GoSublime#862] opened 2018-09-12 04:33 UTC
Hi, 
I'm having trouble running goimports automatically when I save a file on Sublime Text 3.
It doesn't auto format (gofmt) or do any goimports tasks.

Hi, I've installed correctly GoSublime + goimports
```
which goimports
/Users/fabrice/workspace/Go/bin/goimports
```

I've also set correctly my GOPATH and PATH : 
```
echo $GOPATH
/Users/fabrice/workspace/Go
```

I've set my GoSublime custom config like that : 
```
{
  "env": {
    "GOPATH": "/Users/fabrice/workspace/Go"
  },
  "fmt_cmd": ["goimports"]
}
```

Any advice?

**Comment by DisposaBoy** [comment] 2018-09-12 06:33
Please read https://margo.sh/b/migrate/ for instructions on switching to the development branch. Please be sure to read all the comments in https://margo.sh/s/extension-example as well, they should explain which GoSublime settings no longer work and what their replacements are.

**Comment by fabdarice** [comment] 2018-09-13 06:43
Hi @DisposaBoy ,

I've followed the instructions clearly https://margo.sh/b/migrate/  by installing GoSublime straight from the github repo using the development branch.

I've also uncommented `golang.GoImports,` in margo.go files.
I see errors clearly being highlighted in my file, however, it still doesn't autoformat on save (i.e: removing whitespace, adding comma at the end).

Any suggestions?

**Comment by DisposaBoy** [comment] 2018-09-13 08:39
Do you see any errors in the Sublime Text console? Does `golang.GoFmt` work?

**Comment by fabdarice** [comment] 2018-09-13 18:03
Whenever I save my file locally, Sublime Text console is showing : 
```
margo: pre-save error in view 101: /Users/fabrice/workspace/Go/src/onchain/database/postgres.go: actions: ViewPreSave, error: failed to fmt /Users/fabrice/workspace/Go/src/onchain/database/postgres.go: exit status 2
```

Also, if I run golang.GoFmt or golang.GoImports manually from the build console, it shows : 
```
[ `golang.GoImports` | done ]
  ``golang.GoImports`` exited: exec: "golang.GoImports": executable file not found in $PATH
```

**Comment by DisposaBoy** [comment] 2018-09-13 20:27
They aren't commands the correct command is `goimports`. Comment out `// golang.GoImports` and un-comment `golang.GoFmt` and save the file, then try on your file.

The `exit status 2` probably means it can't find the `goimports` command. You have to install `goimports` manually.

**Comment by fabdarice** [comment] 2018-09-14 03:06
```
which goimports
/Users/fabrice/workspace/Go/bin/goimports
```

after commenting out golang.GoImports and un-comment golang.GoFmt in margo.go : 
```
[ `golang.GoFmt` | done ]
  ``golang.GoFmt`` exited: exec: "golang.GoFmt": executable file not found in $PATH
```

**Comment by dr2chase** [comment] 2018-09-17 17:38
I think this is not pilot error, I also see a lack of formatting on save, after successfully changing to the dev branch and then (as far as I know) "touching nothing".  I'm here to make this comment because I was getting puzzled and frustrated at this apparent regression and looking to see what other people had reported.

I've read those instructions; I'm going to re-read them, but please consider the possibility that this is a real bug, not a user error of some sort.

Also, when you say something like "Does golang.GoFmt work?" please also include the exact steps we ought to take to accomplish the thing called "golang.GoFmt".  Is that letters I type somewhere?  Where?  I legitimately don't know what you mean when you say that; I would guess, which generates frustration for me, and bad data for you.

**Comment by dr2chase** [comment] 2018-09-17 19:06
Note -- it works on one Go file (in a window lacking project sidebar), not in another (with project sidebar).  I will keep poking at this to see if I can figure spot a pattern.

**Comment by DisposaBoy** [comment] 2018-09-17 20:06
Maybe the lack of docs is making things harder to understand. If I can make that clearer, file new issues or otherwise let me know.

Hopefully this isn't too long to follow...

The gist of it is that GoSublime is moving towards being only a UI that talks to the `margo.sublime` process.

To configure margo, you edit the package called `margo` located at `$Packages/User/GoSublime/src/margo`.
If you press <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd> or <kbd>super+.</kbd>,<kbd>super+x</kbd> on Mac, GoSublime will open it for you. If the package doesn't exist, it will create it for you, using this file https://margo.sh/s/extension-example as base.

If you read that file, you will see a call to `m.Use(` with a list of objects. These objects are called reducers and they provide all the functionality available in GoSublime. e.g. code fmt'ting when you save a `.go` file or press <kbd>ctrl+.</kbd>,<kbd>ctrl+f</kbd>.

For the most part this is also how you configure GoSublime now - just edit that file and save it. After you save a file in the `margo` package (by default, `margo.go`), margo will recompile itself and restart.

Most of the old GoSublime settings file is ignored, but if you read https://margo.sh/s/extension-example the replacement reducers for the old settings are marked with comments starting with `// gs:`.

To get code fmt for `.go` files, you use either the `golang.GoFmt` reducer *or* the `golang.GoImports` reducer. You can see them listed, but commented out here https://github.com/KurokuLabs/margo/blob/master/extension-example/extension-example.go#L68

They're objects in the `margo.sh/golang` package, they're not commands, so if you press <kbd>ctrl+9</kbd> and run `golang.GoFmt`, it will fail.

The `golang.GoFmt` reducer is using the `go/format` package, so once margo compiles, the only way it can fail is if the code has syntax errors. These will be printed in the Sublime Text console <kbd>ctrl+\`</kbd>.

For `golang.GoImports`, due to complications with `GOPATH`, I stopped using the package and instead, it calls the command `goimports`. The downside is that it's not bundled, so you have to install it yourself and make sure it's in the `$PATH`. The problem with GUI apps esp. on Linux and Mac is that they often don't see the same env vars as your terminal, because your `.bashrc`, etc. files aren't being loaded at login. GoSublime tries to work around this by manually running your `$SHELL` and fetching some of the env vars, but it doesn't always succeed. For this reason, you cannot verify that the `goimports` command works by running it in your terminal; you must run it from inside Sublime Text. You can open `9o` <kbd>ctrl+9</kbd> and run `goimports -h` to verify that it works.

Like the `golang.GoFmt` reducer, `golang.GoImports` will refuse to fmt the file in  the face of any type of error. So if there's a syntax error and `goimports` prints to `stderr` or otherwise return a non-zero status code it will not fmt the file. It will, instead, just print an error in the Sublime Text console.

In @fabdarice's case, the error in the console is `... exit status 2` where `status 2` suggests that running `goimports` failed. Either the command cannot be found or there is a syntax error in the file.

Since the error doesn't contain much info, the easiest way to debug that situation is to use the `golang.GoFmt` reducer instead of `golang.GoImports` because it only has the 1 failure mode and gives a better error message.

**Comment by dr2chase** [comment] 2018-09-17 20:52
I'm going to read on, but the first nit is that
"If you press ctrl+.,ctrl+x or super+.,super+x on Mac"
does not do what you expect it to.  I did nonetheless find and open margo.go, which was already present.

fan-9 + `goimports -h` gave me
```
[ ~/Library/Application Support/Sublime Text 3/Packages/GoSublime/ ] # 
[ `goimports -h` | done ]
	usage: goimports [flags] [path ...]
	  -cpuprofile string
	    	CPU profile output
	  -d	display diffs instead of rewriting files
	  -e	report all errors (not just the first 10 on different lines)
	  -l	list files whose formatting differs from goimport's
	  -local string
	    	put imports beginning with this string after 3rd-party packages
	  -memprofile string
	    	memory profile output
	  -memrate int
	    	if > 0, sets runtime.MemProfileRate
	  -srcdir dir
	    	choose imports as if source code is from dir. When operating on a single file, dir may instead be the complete file name.
	  -trace string
	    	trace profile output
	  -v	verbose logging
	  -w	write result to (source) file instead of stdout
	``goimports -h`` exited: exit status 2
[ ~/work/go-quick/src/cmd/compile/internal/gc/ ] # 
```
and I made sure to do this with the window open where saving the file did NOT run gofmt.

margo.go contains:
```
func Margo(m mg.Args) {
	// See the documentation for `mg.Reducer`
	// comments beginning with `gs:` denote features that replace old GoSublime settings

	// add our reducers (margo plugins) to the store
	// they are run in the specified order
	// and should ideally not block for more than a couple milliseconds
	m.Use(
		mg.NewReducer(func(mx *mg.Ctx) *mg.State {
			// By default, events (e.g. ViewSaved) are triggered in all files.
			// Replace `mg.AllLangs` with `mg.Go` to restrict events to Go(-lang) files.
			// Please note, however, that this mode is not tested
			// and saving a non-go file will not trigger linters, etc. for that go pkg
			return mx.SetConfig(mx.Config.EnabledForLangs(
				mg.AllLangs,
			))
		}),

		// Add `go` command integration
		// this adds a new commands:
		// gs: these commands are all callable through 9o:
		// * go: Wrapper around the go command, adding linter support
		// * go.play: Automatically build and run go commands or run go test for packages
		//   with support for linting and unsaved files
		// * go.replay: Wrapper around go.play limited to a single instance
		//   by default this command is bound to ctrl+.,ctrl+r or cmd+.,cmd+r
		//
		// UserCmds are also added for `Go Play` and `Go RePlay`
		&golang.GoCmd{},

		// add the day and time to the status bar
		&DayTimeStatus{},

		// both GoFmt and GoImports will automatically disable the GoSublime version
		// you will need to install the `goimports` tool manually
		// https://godoc.org/golang.org/x/tools/cmd/goimports
		//
		// gs: this replaces settings `fmt_enabled`, `fmt_tab_indent`, `fmt_tab_width`, `fmt_cmd`
		//
		golang.GoFmt,
		// or
		// golang.GoImports,
```

Again, formatting works for some files, but not others.  Could this be caused by running 1.10? (I'm about to fix this, but it was finding 1.10.) Are there any diagnostics I should be looking for?

**Comment by DisposaBoy** [comment] 2018-09-17 21:19
> "If you press ctrl+.,ctrl+x or super+.,super+x on Mac"

I don't have a access to a Mac to check right now, but that's what I set the key bindings to. You can see what Sublime Text is using by opening the Sublime Text command palette and typing `Edit Margo Extension`.

Does pressing <kbd>super+.</kbd>,<kbd>super+f</kbd> do anything? To be clear, you probably need to keep holding <kbd>super</kbd> then press <kbd>dot</kbd> immediately followed by <kbd>x, f, etc.</kbd>

If `golang.GoFmt` fails it should print an error message in the Sublime Text console. I don't think the Go version should have any effect on it working or not.


You can also try this reducer which prints a message to the Sublime Text console when you save the file or press <kbd>super+.</kbd>,<kbd>super+f</kbd>. It doesn't do anything else, but should at least confirm whether or not the actions are being sent when you save the file.

		mg.NewReducer(func(mx *mg.Ctx) *mg.State {
			switch mx.Action.(type) {
			case mg.ViewPreSave, mg.ViewFmt:
				mx.Log.Dbg.Printf("Fmt action? %T\n", mx.Action)
			}
			return mx.State
		}),

**Comment by dr2chase** [comment] 2018-09-17 21:33
Does "try this reducer" mean
1. simply add it to the parameter list in the call to m.Use,
2. replace the first parameter,
3. or replace golang.GoFmt?

I haven't figured out where the other source code is, I don't know what the types are, none of this looks obviously incorrect or correct.

**Comment by DisposaBoy** [comment] 2018-09-17 21:33
That's weird. Is there anything different about those files that fail? like non-latin chars, non-utf8 encoded, etc. It seems it doesn't work because margo stops, but doesn't appear to show an error why. This usually means the msgpack encoding/decoding failed in some way.

By `Definition and Reference tooltips` do you mean in the status bar? those are provided by the `&golang.GocodeCalltips{}` reducer.

**Comment by DisposaBoy** [comment] 2018-09-17 21:34
Option `1`, just add it to the parameter list.

**Comment by dr2chase** [comment] 2018-09-17 21:54
The snippets I see show up in a rectangular box when the mouse is over an identifier.

With the additional reducer added (second in list) in the file that doesn't reformat properly, I get this.
```
[17:47:47] margo: pre-save error in view 57: /Users/drchase/work/go-quick/src/cmd/compile/internal/gc/esc.go: agent stopping. request aborted
[17:47:47] margo: agent#011: log: DBG: margo.go:31: Fmt action? mg.ViewPreSave
[17:47:47] margo: agent#011: stopping
[17:47:47] margo: agent#012: starting
[17:47:47] margo: agent#012: ['/Users/drchase/Library/Application Support/Sublime Text 3/Packages/GoSublime/bin/margo.sh', 'start', 'margo.sublime', '-codec', 'msgpack']
[17:47:47] margo: agent#012: log: Using margo extension: /Users/drchase/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/src/margo
[17:47:47] margo: agent#012: log: ``` go install -v -tags="margo margo_extension" margo.sh/cmd/margo.sublime ```
[17:47:47] margo: agent#012: log: ``` "/Users/drchase/Library/Application Support/Sublime Text 3/Packages/GoSublime/bin/margo.sublime" -codec msgpack ```
[17:47:47] margo: agent#012: log: store.go:137: started
[17:47:48] margo: agent#012: log: ``` go install margo.sh/vendor/golang.org/x/tools/cmd/guru ```
[17:48:49] margo: pre-save error in view 57: /Users/drchase/work/go-quick/src/cmd/compile/internal/gc/esc.go: agent stopping. request aborted
[17:48:49] margo: agent#012: log: DBG: margo.go:31: Fmt action? mg.ViewPreSave
[17:48:49] margo: agent#012: stopping
[17:48:49] margo: agent#013: starting
[17:48:49] margo: agent#013: ['/Users/drchase/Library/Application Support/Sublime Text 3/Packages/GoSublime/bin/margo.sh', 'start', 'margo.sublime', '-codec', 'msgpack']
[17:48:49] margo: agent#013: log: Using margo extension: /Users/drchase/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/src/margo
[17:48:49] margo: agent#013: log: ``` go install -v -tags="margo margo_extension" margo.sh/cmd/margo.sublime ```
[17:48:50] margo: agent#013: log: ``` "/Users/drchase/Library/Application Support/Sublime Text 3/Packages/GoSublime/bin/margo.sublime" -codec msgpack ```
[17:48:50] margo: agent#013: log: store.go:137: started
[17:48:50] margo: agent#013: log: ``` go install margo.sh/vendor/golang.org/x/tools/cmd/guru ```
```

**Comment by dr2chase** [comment] 2018-09-17 22:08
File being edited is https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/esc.go

It's specific to THAT FILE.
Others in the same directory, they are fine.
Excuse me while I go walk in circles and curse for a while.

Does your formatter understand "goto"?

**Comment by DisposaBoy** [comment] 2018-09-17 22:20
> The snippets I see show up in a rectangular box when the mouse is over an identifier.

Those would be provided by Sublime Text or another plugin, GoSublime/margo (currently) only uses the status bar.
If it's Sublime Text, you can turn it on/off using the `"show_definitions": true,` or `"show_definitions": false,` setting <kbd>Command Palette > Preferences: Settings</kbd>

> With the additional reducer added (second in list) in the file that doesn't reformat properly, I get this.

That confirms it's margo exiting *after* the file possibly gets fmt'd, but I have no idea why.

Does it happen if you trigger fmt only, i.e. <kbd>super+.</kbd>,<kbd>super+f</kbd> (does that key binding even work for you?)

If it also fails, can you comment out `golang.GoFmt` (in addition to `golang.GoImports`)? maybe it's changing the file contents in some problematic way. 
 
> File being edited is https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/esc.go

I tried that file as well as the copy from `go1.11` and I it works fine on Linux.

Out of curiosity, have you updated Sublime Text recently? I notice you're on version 3176 which has some instability on Mac https://github.com/SublimeTextIssues/Core/issues/2327

**Comment by dr2chase** [comment] 2018-09-17 22:28
Sublime Text claims "no update available".

super+., super+f "works" in the sense of apparently trying to do the format.

Console says:
```
[18:27:14] margo: fmt error in view 57: /Users/drchase/work/go-quick/src/cmd/compile/internal/gc/esc.go: agent stopping. request aborted
[18:27:14] margo: agent#030: log: DBG: margo.go:31: Fmt action? mg.ViewFmt
[18:27:14] margo: agent#030: stopping
```

**Comment by DisposaBoy** [comment] 2018-09-17 22:29
I think I might be able to reproduce this, but it's 23:30 here so I'll have to check it out tomorrow.

**Comment by DisposaBoy** [comment] 2018-09-18 14:06
I found+fixed a bug that seemed to cause it. I can't reproduce any failure after that fix. Do a `git pull` to update to the latest release and try again.

**Comment by dr2chase** [comment] 2018-09-18 14:37
I am no longer able to reproduce the bug after update. Thanks!
Not sure the bug-in-comments was the same as the bug-that-was-filed.

**Closed** 2018-11-08 19:15 UTC
