### ISSUE TITLE
GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by copysunday** [DisposaBoy/GoSublime#626] opened 2015-05-27 14:53 UTC
GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\Go\\bin\\go.exe', 'build', '-v', '-x', '-o', 'gosublime.margo_r14.12.06-1_go?.exe', 'gosubli.me/margo']`
|                > stdout: ``
|                > stderr:`WORK=C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403
|                > gosubli.me/something-borrowed/gocode
|                > mkdir -p $WORK\gosubli.me\something-borrowed\gocode_obj\
|                > mkdir -p $WORK\gosubli.me\something-borrowed\
|                > cd D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode
|                > "C:\Go\pkg\tool\windows_386\8g.exe" -o "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403\gosubli.me\something-borrowed\gocode.a" -trimpath "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403" -p gosubli.me/something-borrowed/gocode -complete -D _/D_/各种软件/Sublime/Data/Packages/GoSublime/src/gosubli.me/something-borrowed/gocode -I "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403" -pack "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\autocompletecontext.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\autocompletefile.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\client.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\config.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\cursorcontext.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\decl.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\declcache.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\formatters.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\gocode.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\gosublime_gocode_bridge.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\os_windows.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\package.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\ripper.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\rpc.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\scope.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\server.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\utils.go"
|                > gosubli.me/something-borrowed/types
|                > mkdir -p $WORK\gosubli.me\something-borrowed\types_obj\
|                > cd D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types
|                > "C:\Go\pkg\tool\windows_386\8g.exe" -o "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403\gosubli.me\something-borrowed\types.a" -trimpath "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403" -p gosubli.me/something-borrowed/types -complete -D _/D_/各种软件/Sublime/Data/Packages/GoSublime/src/gosubli.me/something-borrowed/types -I "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403" -pack "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\api.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\builtins.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\check.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\const.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\conversions.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\errors.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\exportdata.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\expr.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\gcimporter.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\objects.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\operand.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\predicates.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\resolve.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\scope.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\sizes.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\stmt.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\types.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\something-borrowed\types\universe.go"
|                > gosubli.me/margo
|                > mkdir -p $WORK\gosubli.me\margo_obj\
|                > mkdir -p $WORK\gosubli.me\margo_obj\exe\
|                > cd D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo
|                > "C:\Go\pkg\tool\windows_386\8g.exe" -o "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403\gosubli.me\margo.a" -trimpath "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403" -p gosubli.me/margo -complete -D _/D_/各种软件/Sublime/Data/Packages/GoSublime/src/gosubli.me/margo -I "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403" -I "D:\各种软件\Sublime\Data\Packages\GoSublime\pkg\windows_386" -pack "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\broker.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\common.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\fx.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\g_autoinst.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_declarations.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_doc.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_env.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_fmt.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_gocode.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_hello.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_import_paths.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_imports.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_kill.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_lint.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_ping.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_pkg.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_pkgdirs.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_pkgdoc.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_pkgpaths.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_play.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_sh.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\m_share.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\main.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\oom.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\pkgpaths.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\registry.go" "D:\各种软件\Sublime\Data\Packages\GoSublime\src\gosubli.me\margo\srcpkg1.4.go"
|                > cd .
|                > "C:\Go\pkg\tool\windows_386\8l.exe" -o "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403\gosubli.me\margo\_obj\exe\a.out.exe" -L "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403" -L "D:\各种软件\Sublime\Data\Packages\GoSublime\pkg\windows_386" -extld=gcc "C:\Users\COPYSU~1\AppData\Local\Temp\go-build477771403\gosubli.me\margo.a"
|                > cp $WORK\gosubli.me\margo_obj\exe\a.out.exe gosublime.margo_r14.12.06-1_go?.exe
|                > go install gosubli.me/margo: open gosublime.margo_r14.12.06-1_go?.exe: The filename, directory name, or volume label syntax is incorrect.`
|                > exception:`None`
|   install state: busy
| sublime.version: 3008
| sublime.channel: stable

**Comment by pbennett** [comment] 2015-07-30 23:42
Duplicate of #638

**Closed** 2018-11-08 18:55 UTC

**Comment by copysunday** [comment] 2019-01-08 01:17
thx~

**Comment by copysunday** [comment] 2019-01-08 01:17
> Duplicate of #638

thx~
