### ISSUE TITLE
so slow when typing, about 1s delay when typing quickly after migrating to GoSublime's development branch.

### ISSUE THREAD

**Issue by wlchn** [DisposaBoy/GoSublime#880] opened 2018-11-06 02:49 UTC
So so slow when typing, about 1s delay when typing quickly. happens after migrating to GoSublime's development branch.

**Comment by DisposaBoy** [comment] 2018-11-06 19:08
I need some info to reproduce this. Maybe try disabling gocode?

**Comment by jonstaryuk** [comment] 2018-11-07 20:11
I'm having a similar issue and it looks like it's gocode.

```
[11:55:53] margo: agent#012: log: gocode.go:178: gocode didn't accept the request after 106ms
[11:55:53] margo: agent#012: log: gocode.go:178: gocode didn't accept the request after 104ms
[11:55:53] margo: agent#012: log: gocode.go:178: gocode didn't accept the request after 102ms
[11:55:54] margo: agent#012: log: gocode.go:178: gocode didn't accept the request after 103ms
[11:55:55] margo: agent#012: log: gocode.go:178: gocode didn't accept the request after 102ms
[11:55:55] margo: agent#012: log: gocode.go:178: gocode didn't accept the request after 101ms
[11:55:55] margo: agent#012: log: gocode.go:178: gocode didn't accept the request after 103ms
[11:55:55] margo: agent#012: log: gocode.go:178: gocode didn't accept the request after 103ms
[11:55:56] margo: agent#012: log: gocode.go:178: gocode didn't accept the request after 104ms
[11:56:09] margo: agent#012: log: gocode.go:194: gocode eventually responded after 16.542s
```

I think it's because I'm using modules outside of GOPATH, and both nsf/gocode and mdempsky/gocode have issues with modules. I installed the [stamblerre/gocode](https://github.com/stamblerre/gocode) fork (which is supposed to support modules according to golang/go#24661) but it doesn't seem to help.

I ran it with `MarGocodeCtl.Debug = true` and it floods the log with hundreds of lines of "cannot find package" failures, which suggests that it's still using one of the old gocode forks without module support.

Does MarGo have gocode compiled-in, or does it call out to `gocode` in the shell path? I'm wondering if I can force it to use the stamblerre/gocode fork.

**Comment by DisposaBoy** [comment] 2018-11-07 20:48
@jonstaryuk It uses a fork of `mdempsky/gocode` but I intensionally don't support modules beyond any basic support that the `go/build` package has because the proposed solution `go/packages` is too slow and doesn't appear to solve any real problem. There is some mention of having some better solution(s) by the release of go1.12 so I'm waiting to see what happens there.

With that said, basic auto-completion *should* work in go1.11 even though I don't actually test it. If it's complaining about not being able to find a package and you can help me reproduce it, then I'm willing to take a look to see if there's anything I can do about it.

**Comment by jonstaryuk** [comment] 2018-11-07 21:02
That makes sense. It seems like everything works if I use `go mod vendor` and move my project back into GOPATH/src, so I'll stick with that, at least until Go 1.12 in February.

**Comment by furagu** [comment] 2018-11-22 13:10
Is there a way to disable `gocode` integration completely? Those keystroke slowdowns are very annoying.

**Comment by DisposaBoy** [comment] 2018-11-22 13:32
@furagu It's better to help me reproduce the issue. That's the only way it'll get fixed.

With that said, your question should be answered by reading the comments in the `margo.go` config file introduced in https://margo.sh/b/hello-margo/.

**Comment by DisposaBoy** [comment] 2018-11-29 10:06
The `next` branch includes an upcoming change that disables the likely cause of this and should *fix* @jonstaryuk's case at the cost of no non-stdlib completion when modules are enabled.

Since no-one else provided any feedback, there's nothing more I can do so I will close this issue.

**Closed by DisposaBoy** 2018-11-29 10:06 UTC

**Comment by nehbit** [comment] 2019-07-23 04:49
Writing in to confirm that switching to the next branch indeed fixed this issue I was facing. I wasn't expecting non-stdlib completion anyway (that would be a huge undertaking) so this was no feature loss for me. Cheers and thanks for making GoSublime!
